=== aomalov/JBT_samples/java and xml for jbt/files/people.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT people (person*)>
<!ELEMENT person (name, age)>
<!ATTLIST person gender (M|F) "M">
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== aomalov/JBT_samples/java and xml for jbt/files/people.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE people SYSTEM "people.dtd">
<people>
	<person gender="M">
		<name>David</name>
		<age>40</age>
	</person>
	<person gender="F">
		<name>Tamar</name>
		<age>35</age>
	</person>
	<person gender="M">
		<name>Moshe</name>
		<age>11</age>
	</person>
</people>
